#define DECK_CARD_LENGTH 54
#define PLAYER_CARD_LENGTH 8
#define TRASH_CARD_LENGTH 1

int deck[DECK_CARD_LENGTH];
int player1Deck[PLAYER_CARD_LENGTH];
int player2Deck[PLAYER_CARD_LENGTH];
int trashDeck[TRASH_CARD_LENGTH];
